Transform: AWS::Serverless-2016-10-31
Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          RUST_LOG: info
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /example
            Method: get
            Cors: "'*'"
Outputs:
  ExampleFunctionArn:
    Description: "Example Lambda Function ARN"
    Value: !GetAtt ExampleFunction.Arn
