AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stingray

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    LoggingConfig:
      LogFormat: JSON

Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          RUST_LOG: info
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /example
            Method: get
            Cors: "'*'"
    Metadata:
      DockerContext: ./backend/example
      Dockerfile: Dockerfile
Outputs:
  ExampleFunctionArn:
    Description: "Example Lambda Function ARN"
    Value: !GetAtt ExampleFunction.Arn
